use crate::comment::{Comment, CommentPosition, SpecialCommentData};
use crate::writer::rows;
use crate::writer::utils;
use std::fmt::Write;
use tracing::warn;

pub fn write_head(
    width: u32,
    height: u32,
    fontface: &str,
    fontsize: f32,
    alpha: f32,
    styleid: &str,
) -> String {
    let alpha = 255 - (alpha * 255.0).round() as u8;
    let outline = f32::max(fontsize / 25.0, 1.0);
    format!("\
[Script Info]
; Script generated by biliass (based on Danmaku2ASS)
; https://github.com/yutto-dev/yutto/tree/main/packages/biliass
Script Updated By: biliass (https://github.com/yutto-dev/yutto/tree/main/packages/biliass)
ScriptType: v4.00+
PlayResX: {width}
PlayResY: {height}
Aspect Ratio: {width}:{height}
Collisions: Normal
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: {styleid}, {fontface}, {fontsize:.0}, &H{alpha:02X}FFFFFF, &H{alpha:02X}FFFFFF, &H{alpha:02X}000000, &H{alpha:02X}000000, 0, 0, 0, 0, 100, 100, 0.00, 0.00, 1, {outline:.0}, 0, 7, 0, 0, 0, 0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"
    )
}

fn convert_type2(row: usize, height: u32, bottom_reserved: u32) -> usize {
    height as usize - bottom_reserved as usize - row
}

// --- Shared style helpers for _to_buf writers ---

/// Write `\fs` override when comment size differs from base fontsize.
#[inline]
fn write_fontsize_override(buf: &mut String, comment_size: f32, base_fontsize: f32) {
    if comment_size - base_fontsize <= -1. || comment_size - base_fontsize >= 1. {
        let _ = write!(buf, "\\fs{:.0}", comment_size);
    }
}

/// Write `\c` color override (and `\3c` outline for black text).
#[inline]
fn write_color_override(buf: &mut String, color: u32) {
    if color != 0xFFFFFF {
        let _ = write!(buf, "\\c&H{}&", utils::convert_color(color, None, None));
        if color == 0x000000 {
            buf.push_str("\\3c&HFFFFFF&");
        }
    }
}

/// Write `\alpha` / `\fad` / `\fade` override.
#[inline]
fn write_alpha_override(buf: &mut String, from_alpha: u8, to_alpha: u8, lifetime: f64) {
    if from_alpha == to_alpha {
        let _ = write!(buf, "\\alpha&H{from_alpha:02X}");
    } else if (from_alpha, to_alpha) == (255, 0) {
        let _ = write!(buf, "\\fad({:.0},0)", lifetime * 1000.);
    } else if (from_alpha, to_alpha) == (0, 255) {
        let _ = write!(buf, "\\fad(0, {:.0})", lifetime * 1000.);
    } else {
        let lt = lifetime * 1000.;
        let _ = write!(
            buf,
            "\\fade({from_alpha}, {to_alpha}, {to_alpha}, 0, {lt:.0}, {lt:.0}, {lt:.0})"
        );
    }
}

/// Write rotation tags `\frx..\fscy` from a rotation result tuple.
#[inline]
fn write_rotation_tags(buf: &mut String, rot: &(f64, f64, f64, f64, f64, f64, f64)) {
    let _ = write!(
        buf,
        "\\frx{:.0}\\fry{:.0}\\frz{:.0}\\fscx{:.0}\\fscy{:.0}",
        rot.2, rot.3, rot.4, rot.5, rot.6
    );
}

// --- Normal comment writer ---

#[allow(clippy::too_many_arguments)]
fn write_comment_impl(
    buf: &mut String,
    comment: &Comment,
    row: usize,
    width: u32,
    height: u32,
    bottom_reserved: u32,
    fontsize: f32,
    duration_marquee: f64,
    duration_still: f64,
    styleid: &str,
) {
    let comment_data = comment
        .data
        .as_normal()
        .expect("comment_data is not normal");
    let (style, duration) = match comment.pos {
        CommentPosition::Bottom => {
            let halfwidth = width / 2;
            (format!("\\an8\\pos({halfwidth}, {row})"), duration_still)
        }
        CommentPosition::Top => {
            let halfwidth = width / 2;
            let row = convert_type2(row, height, bottom_reserved);
            (format!("\\an2\\pos({halfwidth}, {row})"), duration_still)
        }
        CommentPosition::Reversed => {
            let neglen = -(comment_data.width.ceil()) as i32;
            (
                format!("\\move({neglen}, {row}, {width}, {row})"),
                duration_marquee,
            )
        }
        _ => {
            let neglen = -(comment_data.width.ceil()) as i32;
            (
                format!("\\move({width}, {row}, {neglen}, {row})"),
                duration_marquee,
            )
        }
    };

    buf.push_str("Dialogue: 2,");
    utils::write_timestamp(buf, comment.timeline);
    buf.push(',');
    utils::write_timestamp(buf, comment.timeline + duration);
    buf.push(',');
    buf.push_str(styleid);
    buf.push_str(",,0000,0000,0000,,{");
    buf.push_str(&style);
    write_fontsize_override(buf, comment.size, fontsize);
    write_color_override(buf, comment.color);
    buf.push('}');
    utils::ass_escape_to_buf(buf, &comment.content);
    buf.push('\n');
}

#[allow(clippy::too_many_arguments)]
pub fn write_normal_comment_to_buf<'a>(
    buf: &mut String,
    rows: &mut rows::Rows<'a>,
    comment: &'a Comment,
    width: u32,
    height: u32,
    bottom_reserved: u32,
    fontsize: f32,
    duration_marquee: f64,
    duration_still: f64,
    styleid: &str,
    reduced: bool,
) {
    let mut row: usize = 0;
    let comment_data = comment
        .data
        .as_normal()
        .expect("comment_data is not normal");
    let rowmax = height - bottom_reserved - comment_data.height as u32;
    while row <= rowmax as usize {
        let freerows = rows::test_free_rows(
            rows,
            comment,
            row,
            width,
            height,
            bottom_reserved,
            duration_marquee,
            duration_still,
        );
        if freerows >= comment_data.height as usize {
            rows::mark_comment_row(rows, comment, row);
            write_comment_impl(
                buf,
                comment,
                row,
                width,
                height,
                bottom_reserved,
                fontsize,
                duration_marquee,
                duration_still,
                styleid,
            );
            return;
        } else {
            row += if freerows == 0 { 1 } else { freerows };
        }
    }
    if !reduced {
        row = rows::find_alternative_row(rows, comment, height, bottom_reserved);
        rows::mark_comment_row(rows, comment, row);
        write_comment_impl(
            buf,
            comment,
            row,
            width,
            height,
            bottom_reserved,
            fontsize,
            duration_marquee,
            duration_still,
            styleid,
        );
    }
}

// --- Special (animated) comment writer ---

#[allow(clippy::too_many_arguments)]
pub fn write_special_comment_to_buf(
    buf: &mut String,
    comment: &Comment,
    width: u32,
    height: u32,
    zoom_factor: (f32, f32, f32),
    styleid: &str,
) {
    let SpecialCommentData {
        rotate_y,
        rotate_z,
        from_x,
        from_y,
        to_x,
        to_y,
        from_alpha,
        to_alpha,
        delay,
        lifetime,
        duration,
        fontface,
        is_border,
    } = comment.data.as_special().expect("comment is not special");
    write_comment_with_animation_to_buf(
        buf,
        comment,
        width,
        height,
        *rotate_y,
        *rotate_z,
        *from_x,
        *from_y,
        *to_x,
        *to_y,
        *from_alpha,
        *to_alpha,
        &comment.content,
        *delay,
        *lifetime,
        *duration,
        fontface,
        *is_border,
        styleid,
        zoom_factor,
    );
}

#[allow(clippy::too_many_arguments)]
fn write_comment_with_animation_to_buf(
    buf: &mut String,
    comment: &Comment,
    width: u32,
    height: u32,
    rotate_y: i64,
    rotate_z: i64,
    from_x: f64,
    from_y: f64,
    to_x: f64,
    to_y: f64,
    from_alpha: u8,
    to_alpha: u8,
    text: &str,
    delay: i64,
    lifetime: f64,
    duration: i64,
    fontface: &str,
    is_border: bool,
    styleid: &str,
    zoom_factor: (f32, f32, f32),
) {
    let from_rotarg = utils::convert_flash_rotation(
        rotate_y as f64,
        rotate_z as f64,
        from_x,
        from_y,
        width as f64,
        height as f64,
    );
    let to_rotarg = utils::convert_flash_rotation(
        rotate_y as f64,
        rotate_z as f64,
        to_x,
        to_y,
        width as f64,
        height as f64,
    );
    if [
        from_rotarg.0,
        from_rotarg.1,
        from_rotarg.2,
        from_rotarg.3,
        from_rotarg.4,
        from_rotarg.5,
        to_rotarg.0,
        to_rotarg.1,
        to_rotarg.2,
        to_rotarg.3,
        to_rotarg.4,
        to_rotarg.5,
    ]
    .into_iter()
    .any(|x| x.is_nan())
    {
        warn!(
            "Invalid rotation arguments: {:?}",
            (rotate_y, rotate_z, from_x, from_y)
        );
        return;
    }

    // Dialogue header
    buf.push_str("Dialogue: -1,");
    utils::write_timestamp(buf, comment.timeline);
    buf.push(',');
    utils::write_timestamp(buf, comment.timeline + lifetime);
    buf.push(',');
    buf.push_str(styleid);
    buf.push_str(",,0,0,0,,{");

    // Position / movement
    let _ = write!(buf, "\\org({}, {})", width / 2, height / 2);
    if (from_rotarg.0, from_rotarg.1) == (to_rotarg.0, to_rotarg.1) {
        let _ = write!(buf, "\\pos({:.0}, {:.0})", from_rotarg.0, from_rotarg.1);
    } else {
        let _ = write!(
            buf,
            "\\move({:.0}, {:.0}, {:.0}, {:.0}, {:.0}, {:.0})",
            from_rotarg.0,
            from_rotarg.1,
            to_rotarg.0,
            to_rotarg.1,
            delay,
            delay + duration
        );
    }

    // Rotation
    write_rotation_tags(buf, &from_rotarg);
    if (from_x, from_y) != (to_x, to_y) {
        let _ = write!(buf, "\\t({}, {}, ", delay as i32, (delay + duration) as i32);
        write_rotation_tags(buf, &to_rotarg);
        buf.push(')');
    }

    // Font, size, color, alpha, border
    if !fontface.is_empty() {
        buf.push_str("\\fn");
        utils::ass_escape_to_buf(buf, fontface);
    }
    let _ = write!(buf, "\\fs{:.0}", comment.size * zoom_factor.0);
    write_color_override(buf, comment.color);
    write_alpha_override(buf, from_alpha, to_alpha, lifetime);
    if !is_border {
        buf.push_str("\\bord0");
    }

    // Close styles, write escaped text
    buf.push('}');
    utils::ass_escape_to_buf(buf, text);
    buf.push('\n');
}
