from collections.abc import Awaitable
from pathlib import Path

class HttpError(Exception): ...
class InvalidUrlError(HttpError): ...
class UnsupportedProtocolError(HttpError): ...
class HttpTimeoutError(HttpError): ...
class HttpTransportError(HttpError): ...
class HttpStatusError(HttpError): ...
class SessionClosedError(HttpError): ...

class NativeResponse:
    @property
    def status_code(self) -> int: ...
    @property
    def url(self) -> str: ...
    @property
    def body(self) -> bytes: ...
    @property
    def is_success(self) -> bool: ...
    def header(self, name: str) -> str | None: ...
    def raise_for_status(self) -> None: ...

class TransferSnapshot:
    @property
    def expected_bytes(self) -> int: ...
    @property
    def origin_bytes(self) -> int: ...
    @property
    def received_bytes(self) -> int: ...
    @property
    def committed_bytes(self) -> int: ...
    @property
    def buffered_pages(self) -> int: ...
    @property
    def window_saturated(self) -> bool: ...
    @property
    def in_flight(self) -> int: ...

class TransferHandle:
    def wait(self) -> Awaitable[None]: ...
    def done(self) -> bool: ...
    def cancel(self) -> None: ...
    def snapshot(self) -> TransferSnapshot: ...
    def result(self) -> int: ...

class TransferWorkerLimit:
    def __init__(self, capacity: int) -> None: ...
    @property
    def capacity(self) -> int: ...

class YuttoSession:
    def __init__(
        self,
        *,
        headers: dict[str, str] | None = ...,
        cookies: dict[str, str] | None = ...,
        proxy: str | None = ...,
        use_system_proxy: bool = ...,
        accept_invalid_certs: bool = ...,
        ca_cert_file: str | Path | None = ...,
        ca_cert_dir: str | Path | None = ...,
        read_timeout: float = ...,
        connect_timeout: float = ...,
    ) -> None: ...
    def get(
        self,
        url: str,
        *,
        params: list[tuple[str, str]] | None = ...,
        headers: dict[str, str] | None = ...,
    ) -> Awaitable[NativeResponse]: ...
    def probe_size(self, url: str) -> Awaitable[int | None]: ...
    def cookie(self, name: str, *, url: str = ...) -> str | None: ...
    def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def start_transfer(
        self,
        sources: list[str],
        target: str | Path,
        expected_size: int,
        *,
        overwrite: bool = ...,
        workers: int = ...,
        block_size: int = ...,
        worker_limit: TransferWorkerLimit | None = ...,
    ) -> TransferHandle: ...
