name: "ðŸ› Bug report"
description: Report an issue with yutto
title: "ðŸ› "
labels: ["bug: pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        éžå¸¸æ„Ÿè°¢ä½ çš„ issue report (à¹‘>Ø‚<à¹‘ï¼‰ï¼Œä¸ºäº†ä½¿æˆ‘ä»¬èƒ½å¤Ÿæ›´å¿«åœ°å®šä½é”™è¯¯æ¥æºï¼Œè¯·å°½å¯èƒ½å®Œæ•´åœ°å¡«å†™æœ¬ Issue è¡¨æ ¼
  - type: textarea
    id: bug-description
    attributes:
      label: é—®é¢˜ç®€è¿°
      description: è¯¦è¿°ä½ æ‰€é‡åˆ°çš„é—®é¢˜ï¼ˆå¦‚æœ‰æŠ¥é”™ä¹Ÿè¯·ç²˜è´´åœ¨è¿™é‡Œï¼‰ï½ž
      placeholder: |
        å¦‚æžœæ–¹ä¾¿ï¼Œè¯·æ·»åŠ  --debug å‚æ•°ä»¥æä¾›æ›´åŠ è¯¦ç»†çš„æŠ¥é”™ä¿¡æ¯
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: å¤çŽ°æ–¹å¼
      description: |
        è¯·åœ¨è¿™é‡Œæä¾›ä½ æ‰€ä½¿ç”¨/è°ƒç”¨ yutto çš„æ–¹å¼ã€‚å¦‚æžœä¸Žç‰¹å®š url æœ‰å…³ï¼Œè¯·ç›´æŽ¥åœ¨å‘½ä»¤ä¸­æä¾›è¯¥ urlã€‚
        ä¸ºäº†èŠ‚çœå½¼æ­¤äº¤æµçš„æ—¶é—´ï¼Œéº»çƒ¦åœ¨æäº¤ issue å‰å¤šæ¬¡æµ‹è¯•è¯¥å‘½ä»¤æ˜¯èƒ½å¤Ÿåå¤å¤çŽ°çš„ï¼ˆéžç½‘ç»œé—®é¢˜ï¼‰ï¼Œ
        å¦‚æžœå¯ä»¥ï¼Œéº»çƒ¦åœ¨æäº¤ issue å‰å¯¹å…¶ä»–çš„æƒ…å†µè¿›è¡Œæµ‹è¯•ï¼Œå¹¶å°†ç›¸å…³ä¿¡æ¯è¯¦ç»†æè¿°åœ¨é—®é¢˜ç®€è¿°ä¸­ï¼Œ
        è¿™é‡Œä»…æä¾›**æœ€å°å¯å¤çŽ°**çš„å‘½ä»¤ï¼ˆæ³¨æ„ï¼Œå¦‚æžœä½¿ç”¨äº†è‡ªå®šä¹‰çš„é…ç½®æ–‡ä»¶ï¼Œè¯·å°†é…ç½®æ–‡ä»¶å†…å®¹ä¸€å¹¶æä¾›ï¼‰ã€‚
      placeholder: "æ³¨æ„åœ¨ç²˜è´´çš„å‘½ä»¤ä¸­éšåŽ»æ‰€æœ‰éšç§ä¿¡æ¯å“¦(*/Ï‰ï¼¼*)"
    validations:
      required: true
  - type: textarea
    id: environment-info
    attributes:
      label: çŽ¯å¢ƒä¿¡æ¯
      description: è¯·å°½å¯èƒ½è¯¦ç»†åœ°ä¾›ä»¥ä¸‹ä¿¡æ¯ï½ž
      placeholder: ä½ çš„çŽ¯å¢ƒä¿¡æ¯ï½ž
      value: |
        -  OS: æ“ä½œç³»ç»Ÿç±»åž‹åŠå…¶ç‰ˆæœ¬å·
        -  Python: Python ç‰ˆæœ¬å· (`python --version`)
        -  yutto: yutto ç‰ˆæœ¬å· (`yutto -v`)
        -  FFmpeg: FFmpeg ç‰ˆæœ¬å· (`ffmpeg -version`)
        -  å¦‚æžœæ˜¯æ˜¾ç¤ºç›¸å…³é—®é¢˜
            -  Shell: Shell ç±»åž‹ (`echo $SHELL`)
            -  Terminal: ç»ˆç«¯ç±»åž‹
        -  Others: å…¶å®ƒä¿¡æ¯
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: é¢å¤–ä¿¡æ¯
      description: è¯·å°½å¯èƒ½æä¾›ä¸€äº›ä½ è®¤ä¸ºå¯èƒ½äº§ç”Ÿè¯¥é—®é¢˜çš„ä¸€äº›åŽŸå› 
      placeholder: å¦‚æœ‰é¢å¤–çš„ä¿¡æ¯ï¼Œè¯·å¡«å†™åœ¨è¿™é‡Œï½ž
    validations:
      required: false
  - type: checkboxes
    id: checkboxes
    attributes:
      label: ä¸€ç‚¹ç‚¹çš„è‡ªæˆ‘æ£€æŸ¥
      description: åœ¨ä½ æäº¤ issue ä¹‹å‰ï¼Œéº»çƒ¦ç¡®è®¤è‡ªå·±æ˜¯å¦å·²ç»å®Œæˆäº†ä»¥ä¸‹æ£€æŸ¥ï¼š
      options:
        - label: å……åˆ†é˜…è¯» [README.md](https://github.com/yutto-dev/yutto)ï¼Œç‰¹åˆ«æ˜¯ä¸Žæœ¬ issue ç›¸å…³çš„éƒ¨åˆ†
          required: true
        - label: å¦‚æžœæ˜¯ç½‘ç»œé—®é¢˜ï¼Œå·²ç»æ£€æŸ¥ç½‘ç»œè¿žæŽ¥ã€è®¾ç½®æ˜¯å¦æ­£å¸¸ï¼Œå¹¶ç»è¿‡å……åˆ†æµ‹è¯•è®¤ä¸ºè¿™æ˜¯ yutto æœ¬èº«çš„é—®é¢˜
          required: true
        - label: æœ¬ issue åœ¨ [issues](https://github.com/yutto-dev/yutto/issues) å’Œ [discussion](https://github.com/yutto-dev/yutto/discussions) ä¸­å¹¶æ²¡æœ‰é‡å¤é—®é¢˜
          required: true
        - label: ç¡®è®¤æ‰€å¸Œæœ›ä¸‹è½½çš„èµ„æºæ˜¯æœ¬äººæœ‰æƒé™èŽ·å–çš„ï¼Œyutto ä¸æä¾›ä»»ä½•è¶…å‡ºæœ¬äººæƒé™çš„èµ„æºä¸‹è½½æ–¹å¼
          required: true
