from pathlib import Path

class TransferSnapshot:
    @property
    def expected_bytes(self) -> int: ...
    @property
    def origin_bytes(self) -> int: ...
    @property
    def received_bytes(self) -> int: ...
    @property
    def committed_bytes(self) -> int: ...
    @property
    def buffered_pages(self) -> int: ...
    @property
    def window_saturated(self) -> bool: ...
    @property
    def in_flight(self) -> int: ...

class TransferHandle:
    def done(self) -> bool: ...
    def cancel(self) -> None: ...
    def snapshot(self) -> TransferSnapshot: ...
    def result(self) -> int: ...

def start_transfer(
    sources: list[str],
    target: str | Path,
    expected_size: int,
    *,
    overwrite: bool = ...,
    headers: dict[str, str] | None = ...,
    source_headers: list[dict[str, str]] | None = ...,
    proxy: str | None = ...,
    use_system_proxy: bool = ...,
    accept_invalid_certs: bool = ...,
    workers: int = ...,
    block_size: int = ...,
) -> TransferHandle: ...
