name: Build and Release (yutto-core)

on:
  push:
    tags:
      - "yutto-core@*"
    branches:
      - main
    paths:
      - "packages/yutto-core/**"
      - ".github/workflows/yutto-core-build-and-release.yml"
      - ".github/workflows/native-build-and-release.yml"
  pull_request:
    paths:
      - "packages/yutto-core/**"
      - "src/yutto/downloader/**"
      - ".github/workflows/yutto-core-build-and-release.yml"
      - ".github/workflows/native-build-and-release.yml"
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-release:
    uses: ./.github/workflows/native-build-and-release.yml
    with:
      working-directory: packages/yutto-core
      artifact-prefix: yutto-core
      release-ref-prefix: refs/tags/yutto-core@
    permissions:
      contents: write
      id-token: write
